name: Mirror latest from lolcat/4get

on:
  schedule:
    - cron: "0 0 */2 * *" # At 00:00 UTC every 2nd day of the month
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Get current commit hash from GitHub
        id: current
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: commit } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'mirror'
            });
            core.setOutput('hash', commit.sha);
            console.log(`Current GitHub hash: ${commit.sha}`);

      - name: Clone Gitea repository as a mirror
        run: |
          git clone --bare https://git.lolcat.ca/lolcat/4get

      - name: Get latest commit hash from Gitea
        id: latest
        run: |
          cd 4get.git
          LATEST_HASH=$(git rev-parse master)
          echo "hash=$LATEST_HASH" >> $GITHUB_OUTPUT
          echo "Latest Gitea hash: $LATEST_HASH"

      - name: Check if update needed
        id: check
        run: |
          if [ "${{ steps.current.outputs.hash }}" != "${{ steps.latest.outputs.hash }}" ]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "✅ New commits found - update needed"
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Repository is up to date"
          fi

      - name: Configure Git
        if: steps.check.outputs.needs_update == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push updates to dpi0/4get 'mirror' branch
        if: steps.check.outputs.needs_update == 'true'
        run: |
          cd 4get.git
          git remote set-url --push origin 'https://x-access-token:${{ secrets.FOURGET_TOKEN }}@github.com/${{ github.repository }}.git'
          git push origin master

      - name: Trigger publish workflow
        if: steps.check.outputs.needs_update == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FOURGET_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "publish.yml",
              ref: "main"
            });
